'use client';
import * as React from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { MonitoringIncident } from '@/lib/monitoring/types';
const sensitiveKey = /(coordinate|latitude|longitude|(^|_)lat($|_)|(^|_)lng($|_)|token|credential|secret|password|history)/i;
function safeMetadata(metadata: MonitoringIncident['metadata']) { return Object.entries(metadata).filter(([key]) => !sensitiveKey.test(key)); }
function timestamp(value: string | null) { if (!value || !Number.isFinite(Date.parse(value))) return 'No disponible'; return new Date(value).toISOString(); }
export function ContextPanelContent({ incident, onFocusMap, onRequestLocation, onSensitiveAction, riderPhone }: { incident: MonitoringIncident | null; onFocusMap?: () => void; onRequestLocation?: () => void; onSensitiveAction?: () => void; riderPhone?: string | null }) { if (!incident) return <div className="p-4 text-sm text-muted-foreground">Selecciona un incidente para ver el contexto.</div>; return <div className="space-y-4"><div><p className="text-xs text-muted-foreground">Incidente</p><p className="font-semibold">#{incident.id} · {incident.type}</p><p className="text-sm">Prioridad: {incident.priority} · Estado: {incident.status}</p><p className="text-xs text-muted-foreground">Primera detección: {timestamp(incident.firstDetectedAt)}</p><p className="text-xs text-muted-foreground">Última detección: {timestamp(incident.lastDetectedAt)}</p></div><div className="space-y-1 text-sm"><p className="font-medium">Contexto seguro</p>{safeMetadata(incident.metadata).map(([key, value]) => <p key={key} className="text-muted-foreground">{key}: {String(value)}</p>)}</div><div className="flex flex-wrap gap-2">{onFocusMap ? <Button size="sm" variant="outline" onClick={onFocusMap}>Enfocar mapa</Button> : null}{onRequestLocation && incident.riderId ? <Button size="sm" variant="outline" onClick={onRequestLocation}>Solicitar ubicación</Button> : null}{onSensitiveAction ? <Button size="sm" variant="outline" onClick={onSensitiveAction}>Cambiar estado</Button> : null}</div><div className="flex flex-wrap gap-3 text-sm">{incident.riderId ? <Link className="underline" href={`/riders/${incident.riderId}`}>Ver rider</Link> : null}{incident.orderId ? <Link className="underline" href={`/orders/${incident.orderId}`}>Ver pedido</Link> : null}{riderPhone ? <><a className="underline" href={`tel:${riderPhone}`}>Llamar</a><a className="underline" href={`https://wa.me/${riderPhone}`}>WhatsApp</a></> : null}</div></div>; }
export function ContextPanel(props: React.ComponentProps<typeof ContextPanelContent>) { return <Card><CardHeader><CardTitle>Contexto operativo</CardTitle></CardHeader><CardContent><ContextPanelContent {...props} /></CardContent></Card>; }
