'use client';
import { AlertCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import type { MonitoringIncident } from '@/lib/monitoring/types';
const priorityLabel = { P1: 'Crítica', P2: 'Alta', P3: 'Media' } as const;
function age(value: string): string { const timestamp = Date.parse(value); if (!Number.isFinite(timestamp)) return 'Edad no disponible'; const minutes = Math.max(0, Math.floor((Date.now() - timestamp) / 60000)); return minutes < 1 ? 'hace <1 min' : minutes < 60 ? `hace ${minutes} min` : `hace ${Math.floor(minutes / 60)} h`; }
export function IncidentQueue({ incidents, selectedId, onSelect, isLoading = false, error = null }: { incidents: MonitoringIncident[]; selectedId: number | null; onSelect: (incident: MonitoringIncident) => void; isLoading?: boolean; error?: string | null }) { return <Card className="flex min-h-0 flex-1 flex-col"><CardHeader><CardTitle className="flex items-center gap-2"><AlertCircle className="h-4 w-4" />Cola de incidentes</CardTitle></CardHeader><CardContent className="min-h-0 flex-1 px-2 pb-2"><ScrollArea className="h-full"><div role="list" aria-label="Incidentes de monitoreo" className="space-y-2">{isLoading ? <p className="p-3 text-sm text-muted-foreground">Cargando incidentes...</p> : error ? <p role="alert" className="p-3 text-sm text-destructive">{error}</p> : incidents.length === 0 ? <p className="p-3 text-sm text-muted-foreground">No hay incidentes activos.</p> : incidents.map((incident) => <div key={incident.id} role="listitem"><Button type="button" variant="ghost" aria-pressed={selectedId === incident.id} className="h-auto w-full justify-start whitespace-normal p-3 text-left" onClick={() => onSelect(incident)}><span className="min-w-0 space-y-1"><span className="flex items-center gap-2"><Badge variant={incident.priority === 'P1' ? 'destructive' : 'outline'}>{incident.priority} · {priorityLabel[incident.priority]}</Badge><span className="text-xs text-muted-foreground">#{incident.id}</span></span><span className="block truncate text-sm font-medium">{incident.type}</span><span className="block text-xs text-muted-foreground">{age(incident.firstDetectedAt)} · {incident.status === 'attending' ? 'Atendiendo' : 'Abierto'}</span></span></Button></div>)}</div></ScrollArea></CardContent></Card>; }
