'use client';

import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Slider } from '@/components/ui/slider';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import type { MonitoringRider } from '@/lib/monitoring/types';

export type RiderHistoryPoint = { id: number; rider_id: string; latitude: number; longitude: number; recorded_at: string; speed?: number | null; course?: number | null; source?: string | null };
export type RiderHistoryPanelProps = { rider: MonitoringRider | null; startAt: string; endAt: string; onStartAtChange?: (value: string) => void; onEndAtChange?: (value: string) => void; onPointsChange?: (points: RiderHistoryPoint[]) => void; onPlaybackPointChange?: (point: RiderHistoryPoint | null) => void };

export function RiderHistoryPanel({ rider, startAt, endAt, onStartAtChange, onEndAtChange, onPointsChange, onPlaybackPointChange }: RiderHistoryPanelProps) {
  const [points, setPoints] = useState<RiderHistoryPoint[]>([]); const [index, setIndex] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [playing, setPlaying] = useState(false); const [playbackSpeed, setPlaybackSpeed] = useState(1); const requestIdRef = useRef(0); const abortRef = useRef<AbortController | null>(null); const playbackCallbackRef = useRef(onPlaybackPointChange); playbackCallbackRef.current = onPlaybackPointChange;
  useEffect(() => () => { abortRef.current?.abort(); }, []);
  useEffect(() => { requestIdRef.current += 1; abortRef.current?.abort(); setPoints([]); setIndex(0); setPlaying(false); setError(null); playbackCallbackRef.current?.(null); }, [rider?.id, startAt, endAt]);
  useEffect(() => { if (!playing || points.length < 2) return; const timer = window.setInterval(() => { setIndex((current) => { const next = Math.min(current + 1, points.length - 1); playbackCallbackRef.current?.(points[next] ?? null); if (next === points.length - 1) setPlaying(false); return next; }); }, Math.max(120, 900 / playbackSpeed)); return () => window.clearInterval(timer); }, [playbackSpeed, playing, points]);
  async function load() {
    if (!rider) return;
    const requestId = requestIdRef.current + 1; requestIdRef.current = requestId; abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; setLoading(true); setError(null);
    try { const response = await fetch('/api/monitoring/history', { method: 'POST', credentials: 'same-origin', cache: 'no-store', signal: controller.signal, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ riderId: rider.id, startAt: new Date(startAt).toISOString(), endAt: new Date(endAt).toISOString() }) }); const payload: unknown = await response.json(); if (requestId !== requestIdRef.current) return; if (!response.ok) throw new Error(payload && typeof payload === 'object' && 'message' in payload && typeof payload.message === 'string' ? payload.message : 'No se pudo consultar el historial.'); const next = payload && typeof payload === 'object' && 'points' in payload && Array.isArray(payload.points) ? payload.points as RiderHistoryPoint[] : []; setPoints(next); setIndex(0); onPointsChange?.(next); onPlaybackPointChange?.(next[0] ?? null); } catch (caught) { if (requestId !== requestIdRef.current || (caught instanceof DOMException && caught.name === 'AbortError')) return; setPoints([]); setError(caught instanceof Error ? caught.message : 'No se pudo consultar el historial.'); } finally { if (requestId === requestIdRef.current) setLoading(false); }
  }
  const changeIndex = (value: number) => { const next = Math.min(value, Math.max(0, points.length - 1)); setIndex(next); onPlaybackPointChange?.(points[next] ?? null); };
  const activePoint = points[index] ?? null;
  return <section className="min-h-0 space-y-4 overflow-y-auto rounded-xl border bg-card p-4" aria-labelledby="history-title"><div><h2 id="history-title" className="font-semibold">Historial de recorrido</h2><p className="text-xs text-muted-foreground">{rider ? `${rider.firstName ?? 'Rider'} ${rider.lastName ?? ''}` : 'Selecciona un rider'}</p></div>{!rider ? <p className="text-sm text-muted-foreground">Selecciona un rider para consultar su ruta.</p> : <><div className="grid gap-3"><div><Label htmlFor="history-start" className="text-xs">Desde</Label><Input id="history-start" type="datetime-local" value={startAt} onChange={(event) => onStartAtChange?.(event.target.value)} /></div><div><Label htmlFor="history-end" className="text-xs">Hasta</Label><Input id="history-end" type="datetime-local" value={endAt} onChange={(event) => onEndAtChange?.(event.target.value)} /></div></div><Button type="button" className="w-full" onClick={() => void load()} disabled={loading}>{loading ? 'Consultando...' : 'Consultar recorrido'}</Button>{error ? <p role="alert" className="text-sm text-red-600">{error}</p> : null}{!loading && !error && points.length === 0 ? <p className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">No hay puntos guardados para ese rango.</p> : null}{points.length > 0 ? <div className="space-y-3 rounded-lg bg-slate-50 p-3"><div className="flex items-center justify-between text-xs"><strong>{points.length} puntos</strong><span>{index + 1}/{points.length}</span></div>{activePoint ? <div className="grid grid-cols-2 gap-2 text-xs"><div><span className="text-muted-foreground">Fecha y hora</span><strong className="block">{new Date(activePoint.recorded_at).toLocaleString('es-MX')}</strong></div><div><span className="text-muted-foreground">Velocidad</span><strong className="block">{Math.round(activePoint.speed ?? 0)} km/h</strong></div></div> : null}<Slider aria-label="Punto de reproducción" value={[index]} max={points.length - 1} step={1} onValueChange={(value) => { setPlaying(false); changeIndex(value[0] ?? 0); }} /><div className="flex flex-wrap gap-2"><Button size="sm" type="button" variant="outline" onClick={() => { setPlaying(false); changeIndex(0); }}>Reiniciar</Button><Button size="sm" type="button" onClick={() => setPlaying((current) => !current)}>{playing ? 'Pausar' : 'Reproducir'}</Button><Select value={String(playbackSpeed)} onValueChange={(value) => setPlaybackSpeed(Number(value))}><SelectTrigger aria-label="Velocidad de reproducción" className="h-9 w-[82px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="1">1x</SelectItem><SelectItem value="2">2x</SelectItem><SelectItem value="4">4x</SelectItem><SelectItem value="8">8x</SelectItem></SelectContent></Select></div></div> : null}</>}</section>;
}
