create table if not exists grupohubs.rider_location_history (
  id bigint generated by default as identity primary key,
  rider_id character varying(255) not null references grupohubs.riders(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  speed double precision null,
  course double precision null,
  recorded_at timestamp with time zone not null,
  source character varying(32) not null default 'rider_app',
  created_at timestamp with time zone not null default now()
);

create index if not exists rider_location_history_rider_id_idx
  on grupohubs.rider_location_history (rider_id);

create index if not exists rider_location_history_recorded_at_idx
  on grupohubs.rider_location_history (recorded_at desc);

create unique index if not exists rider_location_history_dedupe_idx
  on grupohubs.rider_location_history (rider_id, recorded_at, latitude, longitude);
