BEGIN;

ALTER TABLE grupohubs.system_settings
  ADD COLUMN IF NOT EXISTS monitoring_unassigned_critical_minutes integer NOT NULL DEFAULT 7,
  ADD COLUMN IF NOT EXISTS monitoring_gps_stale_critical_minutes integer NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS monitoring_stopped_in_transit_minutes integer NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS monitoring_meaningful_movement_meters integer NOT NULL DEFAULT 50;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'system_settings_monitoring_unassigned_minutes_check'
      AND conrelid = 'grupohubs.system_settings'::regclass
  ) THEN
    ALTER TABLE grupohubs.system_settings
      ADD CONSTRAINT system_settings_monitoring_unassigned_minutes_check
      CHECK (monitoring_unassigned_critical_minutes > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'system_settings_monitoring_gps_stale_minutes_check'
      AND conrelid = 'grupohubs.system_settings'::regclass
  ) THEN
    ALTER TABLE grupohubs.system_settings
      ADD CONSTRAINT system_settings_monitoring_gps_stale_minutes_check
      CHECK (monitoring_gps_stale_critical_minutes > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'system_settings_monitoring_stopped_minutes_check'
      AND conrelid = 'grupohubs.system_settings'::regclass
  ) THEN
    ALTER TABLE grupohubs.system_settings
      ADD CONSTRAINT system_settings_monitoring_stopped_minutes_check
      CHECK (monitoring_stopped_in_transit_minutes > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'system_settings_monitoring_movement_meters_check'
      AND conrelid = 'grupohubs.system_settings'::regclass
  ) THEN
    ALTER TABLE grupohubs.system_settings
      ADD CONSTRAINT system_settings_monitoring_movement_meters_check
      CHECK (monitoring_meaningful_movement_meters > 0);
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS grupohubs.monitoring_incidents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condition_key text NOT NULL,
  incident_type varchar(64) NOT NULL,
  priority varchar(2) NOT NULL CHECK (priority IN ('P1', 'P2', 'P3')),
  rider_id varchar(255),
  order_id varchar(255),
  status varchar(20) NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'attending', 'resolved')),
  first_detected_at timestamptz NOT NULL,
  last_detected_at timestamptz NOT NULL,
  attending_at timestamptz,
  resolved_at timestamptz,
  last_acted_by_user_id varchar(255),
  resolution_source varchar(40),
  resolution_reason text,
  condition_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT monitoring_incidents_detection_order_check
    CHECK (last_detected_at >= first_detected_at),
  CONSTRAINT monitoring_incidents_attending_timestamp_check
    CHECK (status <> 'attending' OR attending_at IS NOT NULL),
  CONSTRAINT monitoring_incidents_resolved_timestamp_check
    CHECK (status <> 'resolved' OR resolved_at IS NOT NULL),
  CONSTRAINT monitoring_incidents_open_timestamps_check
    CHECK (status <> 'open' OR (attending_at IS NULL AND resolved_at IS NULL)),
  CONSTRAINT monitoring_incidents_attending_resolution_check
    CHECK (status <> 'attending' OR resolved_at IS NULL),
  CONSTRAINT monitoring_incidents_attending_order_check
    CHECK (attending_at IS NULL OR attending_at >= first_detected_at),
  CONSTRAINT monitoring_incidents_resolution_order_check
    CHECK (resolved_at IS NULL OR resolved_at >= first_detected_at),
  CONSTRAINT monitoring_incidents_resolution_after_attending_check
    CHECK (resolved_at IS NULL OR attending_at IS NULL OR resolved_at >= attending_at),
  CONSTRAINT monitoring_incidents_metadata_object_check
    CHECK (jsonb_typeof(condition_metadata) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS monitoring_incidents_active_condition_uidx
  ON grupohubs.monitoring_incidents (condition_key)
  WHERE status IN ('open', 'attending');

CREATE INDEX IF NOT EXISTS monitoring_incidents_active_priority_idx
  ON grupohubs.monitoring_incidents (priority, first_detected_at, id)
  WHERE status IN ('open', 'attending');

CREATE INDEX IF NOT EXISTS monitoring_incidents_active_order_idx
  ON grupohubs.monitoring_incidents (order_id, first_detected_at DESC, id DESC)
  WHERE status IN ('open', 'attending') AND order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS monitoring_incidents_active_rider_idx
  ON grupohubs.monitoring_incidents (rider_id, first_detected_at DESC, id DESC)
  WHERE status IN ('open', 'attending') AND rider_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS grupohubs.monitoring_action_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_type varchar(64) NOT NULL,
  acting_user_id varchar(255) NOT NULL,
  rider_id varchar(255),
  order_id varchar(255),
  incident_id bigint,
  is_sensitive boolean NOT NULL DEFAULT false,
  reason text,
  result varchar(20) NOT NULL CHECK (result IN ('success', 'failed')),
  safe_error_category varchar(64),
  before_values jsonb NOT NULL DEFAULT '{}'::jsonb,
  after_values jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT monitoring_action_log_sensitive_reason_check
    CHECK (is_sensitive IS FALSE OR nullif(btrim(reason), '') IS NOT NULL),
  CONSTRAINT monitoring_action_log_failed_category_check
    CHECK (result <> 'failed' OR safe_error_category IS NOT NULL),
  CONSTRAINT monitoring_action_log_error_category_nonempty_check
    CHECK (safe_error_category IS NULL OR nullif(btrim(safe_error_category), '') IS NOT NULL),
  CONSTRAINT monitoring_action_log_before_values_object_check
    CHECK (jsonb_typeof(before_values) = 'object'),
  CONSTRAINT monitoring_action_log_after_values_object_check
    CHECK (jsonb_typeof(after_values) = 'object')
);

CREATE INDEX IF NOT EXISTS monitoring_action_log_created_idx
  ON grupohubs.monitoring_action_log (created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS monitoring_action_log_incident_created_idx
  ON grupohubs.monitoring_action_log (incident_id, created_at DESC, id DESC)
  WHERE incident_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS monitoring_action_log_order_created_idx
  ON grupohubs.monitoring_action_log (order_id, created_at DESC, id DESC)
  WHERE order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS monitoring_action_log_rider_created_idx
  ON grupohubs.monitoring_action_log (rider_id, created_at DESC, id DESC)
  WHERE rider_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS monitoring_action_log_actor_created_idx
  ON grupohubs.monitoring_action_log (acting_user_id, created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION grupohubs.reject_monitoring_action_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, grupohubs
AS $$
BEGIN
  RAISE EXCEPTION 'monitoring_action_log is append-only';
END;
$$;

DROP TRIGGER IF EXISTS monitoring_action_log_append_only
  ON grupohubs.monitoring_action_log;

CREATE TRIGGER monitoring_action_log_append_only
BEFORE UPDATE OR DELETE ON grupohubs.monitoring_action_log
FOR EACH ROW
EXECUTE FUNCTION grupohubs.reject_monitoring_action_log_mutation();

CREATE INDEX IF NOT EXISTS orders_monitoring_unassigned_created_idx
  ON grupohubs.orders (created_at, id)
  WHERE rider_id IS NULL AND status = 'pending_acceptance';

CREATE INDEX IF NOT EXISTS orders_monitoring_rider_status_idx
  ON grupohubs.orders (rider_id, status)
  WHERE rider_id IS NOT NULL;

REVOKE ALL ON TABLE grupohubs.monitoring_incidents
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE grupohubs.monitoring_incidents TO service_role;

REVOKE ALL ON SEQUENCE grupohubs.monitoring_incidents_id_seq
  FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE grupohubs.monitoring_incidents_id_seq TO service_role;

REVOKE ALL ON TABLE grupohubs.monitoring_action_log
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT ON TABLE grupohubs.monitoring_action_log TO service_role;
REVOKE UPDATE, DELETE ON TABLE grupohubs.monitoring_action_log FROM service_role;

REVOKE ALL ON SEQUENCE grupohubs.monitoring_action_log_id_seq
  FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE grupohubs.monitoring_action_log_id_seq TO service_role;

COMMIT;
