BEGIN;

CREATE TABLE grupohubs.admin_web_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash text NOT NULL UNIQUE,
  user_id varchar(255) NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz
);

COMMENT ON TABLE grupohubs.admin_web_sessions IS
  'Revocable admin web sessions. Raw session tokens are never stored; only SHA-256 hashes are persisted.';

CREATE INDEX admin_web_sessions_active_user_expires_idx
  ON grupohubs.admin_web_sessions (user_id, expires_at DESC)
  WHERE revoked_at IS NULL;

REVOKE ALL ON TABLE grupohubs.admin_web_sessions
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE grupohubs.admin_web_sessions TO service_role;

REVOKE ALL ON SEQUENCE grupohubs.admin_web_sessions_id_seq
  FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE grupohubs.admin_web_sessions_id_seq TO service_role;

COMMIT;
