-- Hi Delivery: location tracking schema foundation
--
-- This migration is intentionally additive. It preserves the current direct
-- rider update flow while adding the fields needed for authenticated/batched
-- ingestion in a later migration.
--
-- Do not enable restrictive RLS or revoke legacy anon writes in this migration.
-- Those changes must happen after the new app ingestion endpoint is deployed.

BEGIN;

-- Current-location projection metadata.
ALTER TABLE grupohubs.riders
  ADD COLUMN IF NOT EXISTS last_location_received_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_location_event_id uuid,
  ADD COLUMN IF NOT EXISTS last_location_sequence bigint,
  ADD COLUMN IF NOT EXISTS tracking_session_id uuid,
  ADD COLUMN IF NOT EXISTS tracking_available_until timestamptz;

COMMENT ON COLUMN grupohubs.riders.last_speed IS
  'Current GPS speed in meters per second. Legacy column retained for compatibility.';
COMMENT ON COLUMN grupohubs.riders.last_course IS
  'Current GPS heading in degrees from 0 inclusive to 360 exclusive.';
COMMENT ON COLUMN grupohubs.riders.last_location_update IS
  'Timestamp captured by the rider device for the current location sample.';
COMMENT ON COLUMN grupohubs.riders.last_location_received_at IS
  'Timestamp generated by PostgreSQL when the current location was accepted.';
COMMENT ON COLUMN grupohubs.riders.tracking_available_until IS
  'Server-side availability lease expiration for future dispatch hardening.';

-- Append-only history metadata. Existing rows are backfilled below.
ALTER TABLE grupohubs.rider_location_history
  ADD COLUMN IF NOT EXISTS event_id uuid,
  ADD COLUMN IF NOT EXISTS batch_id uuid,
  ADD COLUMN IF NOT EXISTS device_id uuid,
  ADD COLUMN IF NOT EXISTS sequence bigint,
  ADD COLUMN IF NOT EXISTS accuracy_m double precision,
  ADD COLUMN IF NOT EXISTS altitude_m double precision,
  ADD COLUMN IF NOT EXISTS speed_mps double precision,
  ADD COLUMN IF NOT EXISTS heading_deg double precision,
  ADD COLUMN IF NOT EXISTS is_mock boolean,
  ADD COLUMN IF NOT EXISTS app_version text,
  ADD COLUMN IF NOT EXISTS received_at timestamptz;

-- Existing history was created by the legacy trigger. Preserve its timestamps
-- and give every row a stable event identity for future idempotent ingestion.
UPDATE grupohubs.rider_location_history
SET
  event_id = COALESCE(
    event_id,
    uuid_generate_v5(
      uuid_ns_url(),
      'legacy-rider-location:' || id::text
    )
  ),
  received_at = COALESCE(received_at, created_at),
  speed_mps = COALESCE(speed_mps, speed),
  heading_deg = COALESCE(heading_deg, course);

ALTER TABLE grupohubs.rider_location_history
  ALTER COLUMN event_id SET NOT NULL,
  ALTER COLUMN received_at SET DEFAULT clock_timestamp(),
  ALTER COLUMN received_at SET NOT NULL;

-- Stable idempotency and history query indexes.
CREATE UNIQUE INDEX IF NOT EXISTS rider_location_history_rider_event_uidx
  ON grupohubs.rider_location_history (rider_id, event_id);

CREATE INDEX IF NOT EXISTS rider_location_history_rider_recorded_idx
  ON grupohubs.rider_location_history (rider_id, recorded_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS riders_active_location_received_idx
  ON grupohubs.riders (is_active_for_orders, last_location_received_at DESC)
  WHERE is_active_for_orders IS TRUE;

CREATE INDEX IF NOT EXISTS riders_tracking_lease_idx
  ON grupohubs.riders (tracking_available_until)
  WHERE is_active_for_orders IS TRUE;

-- Existing data is valid according to the diagnostic. These checks protect
-- future writes without changing the current application contract.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'riders_last_latitude_range_check'
      AND conrelid = 'grupohubs.riders'::regclass
  ) THEN
    ALTER TABLE grupohubs.riders
      ADD CONSTRAINT riders_last_latitude_range_check
      CHECK (last_latitude IS NULL OR last_latitude BETWEEN -90 AND 90);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'riders_last_longitude_range_check'
      AND conrelid = 'grupohubs.riders'::regclass
  ) THEN
    ALTER TABLE grupohubs.riders
      ADD CONSTRAINT riders_last_longitude_range_check
      CHECK (last_longitude IS NULL OR last_longitude BETWEEN -180 AND 180);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'riders_last_speed_nonnegative_check'
      AND conrelid = 'grupohubs.riders'::regclass
  ) THEN
    ALTER TABLE grupohubs.riders
      ADD CONSTRAINT riders_last_speed_nonnegative_check
      CHECK (last_speed IS NULL OR last_speed >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'riders_last_course_range_check'
      AND conrelid = 'grupohubs.riders'::regclass
  ) THEN
    ALTER TABLE grupohubs.riders
      ADD CONSTRAINT riders_last_course_range_check
      CHECK (last_course IS NULL OR (last_course >= 0 AND last_course < 360));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'rider_location_history_latitude_range_check'
      AND conrelid = 'grupohubs.rider_location_history'::regclass
  ) THEN
    ALTER TABLE grupohubs.rider_location_history
      ADD CONSTRAINT rider_location_history_latitude_range_check
      CHECK (latitude BETWEEN -90 AND 90);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'rider_location_history_longitude_range_check'
      AND conrelid = 'grupohubs.rider_location_history'::regclass
  ) THEN
    ALTER TABLE grupohubs.rider_location_history
      ADD CONSTRAINT rider_location_history_longitude_range_check
      CHECK (longitude BETWEEN -180 AND 180);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'rider_location_history_speed_nonnegative_check'
      AND conrelid = 'grupohubs.rider_location_history'::regclass
  ) THEN
    ALTER TABLE grupohubs.rider_location_history
      ADD CONSTRAINT rider_location_history_speed_nonnegative_check
      CHECK (speed IS NULL OR speed >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'rider_location_history_course_range_check'
      AND conrelid = 'grupohubs.rider_location_history'::regclass
  ) THEN
    ALTER TABLE grupohubs.rider_location_history
      ADD CONSTRAINT rider_location_history_course_range_check
      CHECK (course IS NULL OR (course >= 0 AND course < 360));
  END IF;
END;
$$;

-- Prevent an offline/retried legacy update from moving the current projection
-- backwards. The historical sample remains accepted by the history trigger.
CREATE OR REPLACE FUNCTION grupohubs.guard_rider_current_location()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, grupohubs
AS $$
BEGIN
  IF TG_OP = 'UPDATE'
     AND NEW.last_location_update IS NOT NULL
     AND OLD.last_location_update IS NOT NULL
     AND NEW.last_location_update < OLD.last_location_update THEN
    NEW.last_latitude := OLD.last_latitude;
    NEW.last_longitude := OLD.last_longitude;
    NEW.last_speed := OLD.last_speed;
    NEW.last_course := OLD.last_course;
    NEW.last_location_update := OLD.last_location_update;
    NEW.last_location_received_at := OLD.last_location_received_at;
    NEW.last_location_event_id := OLD.last_location_event_id;
    NEW.last_location_sequence := OLD.last_location_sequence;
  ELSIF NEW.last_latitude IS NOT NULL
        AND NEW.last_longitude IS NOT NULL
        AND NEW.last_location_update IS NOT NULL THEN
    NEW.last_location_received_at := clock_timestamp();
    IF TG_OP = 'INSERT'
       OR NEW.last_location_event_id IS NOT DISTINCT FROM OLD.last_location_event_id THEN
      NEW.last_location_event_id := gen_random_uuid();
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS riders_guard_current_location ON grupohubs.riders;

CREATE TRIGGER riders_guard_current_location
BEFORE UPDATE OF last_latitude, last_longitude, last_speed, last_course, last_location_update
ON grupohubs.riders
FOR EACH ROW
EXECUTE FUNCTION grupohubs.guard_rider_current_location();

-- Keep the legacy history trigger active, but write the new metadata for all
-- future direct updates. New ingestion will later use event_id explicitly.
CREATE OR REPLACE FUNCTION grupohubs.capture_rider_location_history()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, grupohubs
AS $$
BEGIN
  IF NEW.last_latitude IS NULL
     OR NEW.last_longitude IS NULL
     OR NEW.last_location_update IS NULL THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE'
     AND NEW.last_latitude IS NOT DISTINCT FROM OLD.last_latitude
     AND NEW.last_longitude IS NOT DISTINCT FROM OLD.last_longitude
     AND NEW.last_location_update IS NOT DISTINCT FROM OLD.last_location_update THEN
    RETURN NEW;
  END IF;

  INSERT INTO grupohubs.rider_location_history (
    rider_id,
    latitude,
    longitude,
    speed,
    course,
    recorded_at,
    source,
    event_id,
    received_at,
    speed_mps,
    heading_deg
  ) VALUES (
    NEW.id,
    NEW.last_latitude,
    NEW.last_longitude,
    NEW.last_speed,
    NEW.last_course,
    NEW.last_location_update,
    'riders_trigger',
    COALESCE(NEW.last_location_event_id, gen_random_uuid()),
    COALESCE(NEW.last_location_received_at, clock_timestamp()),
    NEW.last_speed,
    NEW.last_course
  )
  ON CONFLICT (rider_id, event_id) DO NOTHING;

  RETURN NEW;
END;
$$;

COMMIT;
