BEGIN;

ALTER TABLE grupohubs.system_settings
  ADD COLUMN IF NOT EXISTS monitoring_unassigned_critical_minutes integer NOT NULL DEFAULT 7,
  ADD COLUMN IF NOT EXISTS monitoring_gps_stale_critical_minutes integer NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS monitoring_stopped_in_transit_minutes integer NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS monitoring_meaningful_movement_meters integer NOT NULL DEFAULT 50;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'system_settings_monitoring_unassigned_minutes_check'
      AND conrelid = 'grupohubs.system_settings'::regclass
  ) THEN
    ALTER TABLE grupohubs.system_settings
      ADD CONSTRAINT system_settings_monitoring_unassigned_minutes_check
      CHECK (monitoring_unassigned_critical_minutes > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'system_settings_monitoring_gps_stale_minutes_check'
      AND conrelid = 'grupohubs.system_settings'::regclass
  ) THEN
    ALTER TABLE grupohubs.system_settings
      ADD CONSTRAINT system_settings_monitoring_gps_stale_minutes_check
      CHECK (monitoring_gps_stale_critical_minutes > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'system_settings_monitoring_stopped_minutes_check'
      AND conrelid = 'grupohubs.system_settings'::regclass
  ) THEN
    ALTER TABLE grupohubs.system_settings
      ADD CONSTRAINT system_settings_monitoring_stopped_minutes_check
      CHECK (monitoring_stopped_in_transit_minutes > 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'system_settings_monitoring_movement_meters_check'
      AND conrelid = 'grupohubs.system_settings'::regclass
  ) THEN
    ALTER TABLE grupohubs.system_settings
      ADD CONSTRAINT system_settings_monitoring_movement_meters_check
      CHECK (monitoring_meaningful_movement_meters > 0);
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS grupohubs.monitoring_incidents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  condition_key text NOT NULL,
  incident_type varchar(64) NOT NULL,
  priority varchar(2) NOT NULL CHECK (priority IN ('P1', 'P2', 'P3')),
  rider_id varchar(255),
  order_id varchar(255),
  status varchar(20) NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'attending', 'resolved')),
  first_detected_at timestamptz NOT NULL,
  last_detected_at timestamptz NOT NULL,
  attending_at timestamptz,
  resolved_at timestamptz,
  last_acted_by_user_id varchar(255),
  resolution_source varchar(40),
  resolution_reason text,
  condition_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT monitoring_incidents_detection_order_check
    CHECK (last_detected_at >= first_detected_at),
  CONSTRAINT monitoring_incidents_attending_timestamp_check
    CHECK (status <> 'attending' OR attending_at IS NOT NULL),
  CONSTRAINT monitoring_incidents_resolved_timestamp_check
    CHECK (status <> 'resolved' OR resolved_at IS NOT NULL),
  CONSTRAINT monitoring_incidents_open_timestamps_check
    CHECK (status <> 'open' OR (attending_at IS NULL AND resolved_at IS NULL)),
  CONSTRAINT monitoring_incidents_attending_resolution_check
    CHECK (status <> 'attending' OR resolved_at IS NULL),
  CONSTRAINT monitoring_incidents_attending_order_check
    CHECK (attending_at IS NULL OR attending_at >= first_detected_at),
  CONSTRAINT monitoring_incidents_resolution_order_check
    CHECK (resolved_at IS NULL OR resolved_at >= first_detected_at),
  CONSTRAINT monitoring_incidents_resolution_after_detection_check
    CHECK (status <> 'resolved' OR resolved_at >= last_detected_at),
  CONSTRAINT monitoring_incidents_resolution_after_attending_check
    CHECK (resolved_at IS NULL OR attending_at IS NULL OR resolved_at >= attending_at),
  CONSTRAINT monitoring_incidents_metadata_object_check
    CHECK (jsonb_typeof(condition_metadata) = 'object')
);

CREATE OR REPLACE FUNCTION grupohubs.prevent_monitoring_incident_reopen()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, grupohubs
AS $$
BEGIN
  IF OLD.status = 'resolved' AND NEW.status <> 'resolved' THEN
    RAISE EXCEPTION 'resolved monitoring incidents cannot be reopened'
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS monitoring_incidents_no_reopen
  ON grupohubs.monitoring_incidents;

CREATE TRIGGER monitoring_incidents_no_reopen
BEFORE UPDATE OF status ON grupohubs.monitoring_incidents
FOR EACH ROW
EXECUTE FUNCTION grupohubs.prevent_monitoring_incident_reopen();

CREATE UNIQUE INDEX IF NOT EXISTS monitoring_incidents_active_condition_uidx
  ON grupohubs.monitoring_incidents (condition_key)
  WHERE status IN ('open', 'attending');

CREATE INDEX IF NOT EXISTS monitoring_incidents_active_priority_age_idx
  ON grupohubs.monitoring_incidents (priority, first_detected_at, id)
  WHERE status IN ('open', 'attending');

CREATE INDEX IF NOT EXISTS monitoring_incidents_active_order_idx
  ON grupohubs.monitoring_incidents (order_id, first_detected_at DESC, id DESC)
  WHERE status IN ('open', 'attending') AND order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS monitoring_incidents_active_rider_idx
  ON grupohubs.monitoring_incidents (rider_id, first_detected_at DESC, id DESC)
  WHERE status IN ('open', 'attending') AND rider_id IS NOT NULL;

CREATE OR REPLACE FUNCTION grupohubs.reconcile_monitoring_incidents(
  p_conditions jsonb,
  p_evaluated_types text[],
  p_now timestamptz
)
RETURNS SETOF grupohubs.monitoring_incidents
LANGUAGE plpgsql
SET search_path = pg_catalog, grupohubs
AS $$
DECLARE
  incompatible_condition_key text;
BEGIN
  IF p_now IS NULL THEN
    RAISE EXCEPTION 'p_now is required' USING ERRCODE = '22023';
  END IF;

  IF p_conditions IS NULL OR jsonb_typeof(p_conditions) <> 'array' THEN
    RAISE EXCEPTION 'p_conditions must be a JSON array' USING ERRCODE = '22023';
  END IF;

  IF p_evaluated_types IS NULL OR EXISTS (
    SELECT 1
    FROM unnest(p_evaluated_types) AS evaluated_type
    WHERE evaluated_type IS NULL
      OR evaluated_type <> ALL (ARRAY[
        'unassigned',
        'gps-stale',
        'stopped-in-transit',
        'dispatch-exhausted',
        'late-delivery',
        'outside-zone',
        'repeated-rejections',
        'irregular-reporting'
      ]::text[])
  ) THEN
    RAISE EXCEPTION 'p_evaluated_types contains an invalid incident type'
      USING ERRCODE = '22023';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_conditions) AS entry(condition)
    WHERE jsonb_typeof(condition) <> 'object'
      OR jsonb_typeof(condition -> 'condition_key') IS DISTINCT FROM 'string'
      OR nullif(btrim(condition ->> 'condition_key'), '') IS NULL
      OR condition ->> 'incident_type' IS NULL
      OR condition ->> 'incident_type' <> ALL (ARRAY[
        'unassigned',
        'gps-stale',
        'stopped-in-transit',
        'dispatch-exhausted',
        'late-delivery',
        'outside-zone',
        'repeated-rejections',
        'irregular-reporting'
      ]::text[])
      OR condition ->> 'priority' IS NULL
      OR condition ->> 'priority' <> ALL (ARRAY['P1', 'P2', 'P3']::text[])
      OR condition ->> 'status' IS DISTINCT FROM 'open'
      OR coalesce(jsonb_typeof(condition -> 'order_id'), 'missing')
        NOT IN ('string', 'null')
      OR coalesce(jsonb_typeof(condition -> 'rider_id'), 'missing')
        NOT IN ('string', 'null')
      OR jsonb_typeof(condition -> 'condition_metadata') IS DISTINCT FROM 'object'
      OR EXISTS (
        SELECT 1
        FROM jsonb_each(condition -> 'condition_metadata') AS metadata(key, value)
        WHERE jsonb_typeof(value) NOT IN ('string', 'number', 'boolean', 'null')
          OR key ~* '(coordinate|latitude|longitude|(^|_)lat($|_)|(^|_)lng($|_)|token|credential|secret|password|history)'
      )
  ) THEN
    RAISE EXCEPTION 'p_conditions contains an invalid or sensitive condition'
      USING ERRCODE = '22023';
  END IF;

  WITH parsed_conditions AS (
    SELECT
      condition ->> 'condition_key' AS condition_key,
      condition ->> 'incident_type' AS incident_type,
      nullif(condition ->> 'order_id', '') AS order_id,
      nullif(condition ->> 'rider_id', '') AS rider_id
    FROM jsonb_array_elements(p_conditions) AS entry(condition)
  )
  SELECT condition_key
  INTO incompatible_condition_key
  FROM parsed_conditions
  GROUP BY condition_key
  HAVING count(DISTINCT (incident_type, order_id, rider_id)) > 1
  ORDER BY condition_key
  LIMIT 1;

  IF incompatible_condition_key IS NOT NULL THEN
    RAISE EXCEPTION 'duplicate condition_key has incompatible identity'
      USING ERRCODE = '22023';
  END IF;

  -- A stable transaction-scoped lock serializes snapshots before upsert and resolution.
  PERFORM pg_advisory_xact_lock(907202608);

  WITH parsed_conditions AS (
    SELECT
      condition ->> 'condition_key' AS condition_key,
      condition ->> 'incident_type' AS incident_type,
      condition ->> 'priority' AS priority,
      nullif(condition ->> 'order_id', '') AS order_id,
      nullif(condition ->> 'rider_id', '') AS rider_id,
      condition -> 'condition_metadata' AS condition_metadata
    FROM jsonb_array_elements(p_conditions) AS entry(condition)
  ),
  deduplicated_conditions AS (
    SELECT DISTINCT ON (condition_key)
      condition_key,
      incident_type,
      priority,
      order_id,
      rider_id,
      condition_metadata
    FROM parsed_conditions
    ORDER BY
      condition_key,
      CASE priority WHEN 'P1' THEN 1 WHEN 'P2' THEN 2 ELSE 3 END,
      condition_metadata::text
  )
  INSERT INTO grupohubs.monitoring_incidents (
    condition_key,
    incident_type,
    priority,
    rider_id,
    order_id,
    status,
    first_detected_at,
    last_detected_at,
    condition_metadata,
    created_at,
    updated_at
  )
  SELECT
    condition_key,
    incident_type,
    priority,
    rider_id,
    order_id,
    'open',
    p_now,
    p_now,
    condition_metadata,
    p_now,
    p_now
  FROM deduplicated_conditions
  ON CONFLICT (condition_key) WHERE status IN ('open', 'attending') DO UPDATE
  SET
    incident_type = CASE
      WHEN EXCLUDED.last_detected_at >= monitoring_incidents.last_detected_at
        THEN EXCLUDED.incident_type
      ELSE monitoring_incidents.incident_type
    END,
    priority = CASE
      WHEN EXCLUDED.last_detected_at >= monitoring_incidents.last_detected_at
        THEN EXCLUDED.priority
      ELSE monitoring_incidents.priority
    END,
    last_detected_at = GREATEST(
      monitoring_incidents.last_detected_at,
      EXCLUDED.last_detected_at
    ),
    condition_metadata = CASE
      WHEN EXCLUDED.last_detected_at >= monitoring_incidents.last_detected_at
        THEN EXCLUDED.condition_metadata
      ELSE monitoring_incidents.condition_metadata
    END,
    updated_at = GREATEST(monitoring_incidents.updated_at, EXCLUDED.updated_at);

  UPDATE grupohubs.monitoring_incidents AS incident
  SET
    status = 'resolved',
    resolved_at = GREATEST(
      p_now,
      incident.last_detected_at,
      coalesce(incident.attending_at, p_now)
    ),
    resolution_source = 'condition_cleared',
    updated_at = GREATEST(incident.updated_at, p_now)
  WHERE incident.status IN ('open', 'attending')
    AND incident.incident_type = ANY (p_evaluated_types)
    AND incident.last_detected_at <= p_now
    AND NOT EXISTS (
      SELECT 1
      FROM jsonb_array_elements(p_conditions) AS entry(condition)
      WHERE condition ->> 'condition_key' = incident.condition_key
    );

  RETURN QUERY
  SELECT active_incident.*
  FROM grupohubs.monitoring_incidents AS active_incident
  WHERE active_incident.status IN ('open', 'attending')
  ORDER BY
    CASE priority WHEN 'P1' THEN 1 WHEN 'P2' THEN 2 ELSE 3 END,
    first_detected_at,
    id;
END;
$$;

CREATE TABLE IF NOT EXISTS grupohubs.monitoring_action_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_type varchar(64) NOT NULL,
  acting_user_id varchar(255) NOT NULL,
  rider_id varchar(255),
  order_id varchar(255),
  incident_id bigint,
  is_sensitive boolean NOT NULL DEFAULT false,
  reason text,
  result varchar(20) NOT NULL CHECK (result IN ('success', 'failed')),
  safe_error_category varchar(64),
  before_values jsonb NOT NULL DEFAULT '{}'::jsonb,
  after_values jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT monitoring_action_log_sensitive_reason_check
    CHECK (is_sensitive IS FALSE OR nullif(btrim(reason), '') IS NOT NULL),
  CONSTRAINT monitoring_action_log_failed_category_check
    CHECK (result <> 'failed' OR safe_error_category IS NOT NULL),
  CONSTRAINT monitoring_action_log_error_category_nonempty_check
    CHECK (safe_error_category IS NULL OR nullif(btrim(safe_error_category), '') IS NOT NULL),
  CONSTRAINT monitoring_action_log_before_values_object_check
    CHECK (jsonb_typeof(before_values) = 'object'),
  CONSTRAINT monitoring_action_log_after_values_object_check
    CHECK (jsonb_typeof(after_values) = 'object')
);

CREATE INDEX IF NOT EXISTS monitoring_action_log_created_idx
  ON grupohubs.monitoring_action_log (created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS monitoring_action_log_incident_created_idx
  ON grupohubs.monitoring_action_log (incident_id, created_at DESC, id DESC)
  WHERE incident_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS monitoring_action_log_order_created_idx
  ON grupohubs.monitoring_action_log (order_id, created_at DESC, id DESC)
  WHERE order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS monitoring_action_log_rider_created_idx
  ON grupohubs.monitoring_action_log (rider_id, created_at DESC, id DESC)
  WHERE rider_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS monitoring_action_log_actor_created_idx
  ON grupohubs.monitoring_action_log (acting_user_id, created_at DESC, id DESC);

CREATE OR REPLACE FUNCTION grupohubs.reject_monitoring_action_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, grupohubs
AS $$
BEGIN
  RAISE EXCEPTION 'monitoring_action_log is append-only';
END;
$$;

DROP TRIGGER IF EXISTS monitoring_action_log_append_only
  ON grupohubs.monitoring_action_log;

CREATE TRIGGER monitoring_action_log_append_only
BEFORE UPDATE OR DELETE ON grupohubs.monitoring_action_log
FOR EACH ROW
EXECUTE FUNCTION grupohubs.reject_monitoring_action_log_mutation();

CREATE INDEX IF NOT EXISTS orders_monitoring_unassigned_created_idx
  ON grupohubs.orders (created_at, id)
  WHERE rider_id IS NULL AND status = 'pending_acceptance';

CREATE INDEX IF NOT EXISTS orders_monitoring_rider_status_idx
  ON grupohubs.orders (rider_id, status)
  WHERE rider_id IS NOT NULL;

REVOKE ALL ON TABLE grupohubs.monitoring_incidents
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE grupohubs.monitoring_incidents TO service_role;

REVOKE ALL ON SEQUENCE grupohubs.monitoring_incidents_id_seq
  FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE grupohubs.monitoring_incidents_id_seq TO service_role;

REVOKE ALL ON FUNCTION grupohubs.reconcile_monitoring_incidents(jsonb, text[], timestamptz)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION grupohubs.reconcile_monitoring_incidents(jsonb, text[], timestamptz)
  TO service_role;

REVOKE ALL ON TABLE grupohubs.monitoring_action_log
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT ON TABLE grupohubs.monitoring_action_log TO service_role;
REVOKE UPDATE, DELETE ON TABLE grupohubs.monitoring_action_log FROM service_role;

REVOKE ALL ON SEQUENCE grupohubs.monitoring_action_log_id_seq
  FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE grupohubs.monitoring_action_log_id_seq TO service_role;

COMMIT;
